apiVersion: v1
kind: ConfigMap
metadata:
  name: redishost
  namespace: default
data:
  REDISHOST: 10.206.84.133
  READ_1_REDISHOST: 10.206.84.132
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-counter
  namespace: default
  labels:
    app: visit-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visit-counter
  template:
    metadata:
      labels:
        app: visit-counter
    spec:
      containers:
        - name: visit-counter
          image: "gcr.io/engineer-cloud-nprod/app:latest"
          env:
            - name: REDISHOST
              valueFrom:
                configMapKeyRef:
                  name: redishost
                  key: REDISHOST
            - name: READ_1_REDISHOST
              valueFrom:
                configMapKeyRef:
                  name: redishost
                  key: READ_1_REDISHOST
          ports:
            - name: http
              containerPort: 8080
